/* This file was initially auto-generated by https://github.com/pmndrs/gltfjsx and then adapted manually */
import type { FC } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

type Props = {
  color: string;
  color2: string;
  position: [number, number, number];
  rotation?: [number, number, number];
  scale?: number;
};

const Shoe: FC<Props> = ({ color, color2, ...props }) => {
  const { nodes, materials } = useGLTF('/shoe.gltf')
  // The following is a read-out of the models contents, all of its
  // meshes, groups and so on.
  return (
    <group {...props} dispose={null}>
      {/* We can alter materials by piercing into them: materia-property={...} */}
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe.geometry}
        material={materials.laces}
        material-envMapIntensity={0.8}
      />
      {/* Or, we define new materials, which now allows full re-use */}
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_1.geometry}>
        <meshStandardMaterial
          color={color}
          aoMap={materials.mesh.aoMap}
          normalMap={materials.mesh.normalMap}
          normalMap-encoding={THREE.LinearEncoding}
          roughnessMap={materials.mesh.roughnessMap}
          metalnessMap={materials.mesh.metalnessMap}
          envMapIntensity={0.8}
        />
      </mesh>
      {/*鞋带孔*/}
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_2.geometry}
        material={materials.caps}
        material-envMapIntensity={0.8}
      />
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_3.geometry}
        material={materials.inner}
        material-envMapIntensity={0.8}
      />
      {/*鞋底*/}
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_4.geometry}
        material={materials.sole}
        material-envMapIntensity={0.8}
      />
      {/*鞋旁装饰*/}
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_5.geometry}
        material={materials.stripes}
        material-envMapIntensity={0.8}
      >
        <meshStandardMaterial
          color={color2}
          aoMap={materials.mesh.aoMap}
          normalMap={materials.mesh.normalMap}
          normalMap-encoding={THREE.LinearEncoding}
          roughnessMap={materials.mesh.roughnessMap}
          metalnessMap={materials.mesh.metalnessMap}
          envMapIntensity={0.8}
        />
      </mesh>
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_6.geometry}
        material={materials.band}
        material-envMapIntensity={0.8}
      />
      <mesh
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.shoe_7.geometry}
        material={materials.patch}
        material-envMapIntensity={0.8}
      />
    </group>
  )
}

export default Shoe

useGLTF.preload('/shoe.gltf')
