/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\piggy_van_junior_3d_print.glb --transform --types
Author: Slava Z. (https://sketchfab.com/slava)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/piggy-van-junior-3d-print-3b088d99e88541028ad116de7f97c641
Title: Piggy Van Junior (3d Print)
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations, useScroll } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    polySurface82_Inserts_Mat_0: THREE.Mesh;
    polySurface83_Headlights_Mat_0: THREE.Mesh;
    polySurface84_Headlights_Mat_0: THREE.Mesh;
    polySurface85_Glass_Mat_0: THREE.Mesh;
    polySurface86_Gray_Mat_0: THREE.Mesh;
    polySurface87_Body_Mat_0: THREE.Mesh;
    polySurface88_Gray_Mat_0: THREE.Mesh;
    polySurface89_Body_Mat_0: THREE.Mesh;
    polySurface90_Glass_Mat_0: THREE.Mesh;
    polySurface91_Body_Mat_0: THREE.Mesh;
    polySurface93_Glass_Mat_0: THREE.Mesh;
    polySurface94_Gray_Mat_0: THREE.Mesh;
    polySurface95_Gray_Mat_0: THREE.Mesh;
    polySurface96_Gray_Mat_0: THREE.Mesh;
    polySurface97_Gray_Mat_0: THREE.Mesh;
    polySurface98_Glass_Mat_0: THREE.Mesh;
    polySurface99_Gray_Mat_0: THREE.Mesh;
    polySurface100_Gray_Mat_0: THREE.Mesh;
    polySurface103_Body_Mat_0: THREE.Mesh;
    polySurface103_Body_Mat_0_1: THREE.Mesh;
    polySurface103_Body_Mat_0_2: THREE.Mesh;
    polySurface104_Body_Mat_0: THREE.Mesh;
    polySurface104_Body_Mat_0_1: THREE.Mesh;
    polySurface104_Body_Mat_0_2: THREE.Mesh;
    polySurface105_Orange_Mat_0: THREE.Mesh;
    polySurface106_Tires_Mat_0: THREE.Mesh;
    polySurface107_Tires_Mat_0: THREE.Mesh;
    polySurface108_Blinkers_Mat_0: THREE.Mesh;
    polySurface109_Blinkers_Mat_0: THREE.Mesh;
    polySurface110_Inserts_Mat_0: THREE.Mesh;
    polySurface111_Gray_Mat_0: THREE.Mesh;
    polySurface112_Gray_Mat_0: THREE.Mesh;
    polySurface113_Orange_Mat_0: THREE.Mesh;
    polySurface114_Tires_Mat_0: THREE.Mesh;
    polySurface115_Tires_Mat_0: THREE.Mesh;
    polySurface116_Inserts_Mat_0: THREE.Mesh;
    polySurface117_Inserts_Mat_0: THREE.Mesh;
    polySurface119_Blinkers_Mat_0: THREE.Mesh;
    polySurface122_Roof_Mat_0: THREE.Mesh;
    polySurface122_Roof_Mat_0_1: THREE.Mesh;
    polySurface123_Roof_Mat_0: THREE.Mesh;
    polySurface124_Inserts_Mat_0: THREE.Mesh;
    polySurface125_Inserts_Mat_0: THREE.Mesh;
    polySurface126_Gray_Mat_0: THREE.Mesh;
    polySurface127_Glass_Mat_0: THREE.Mesh;
    polySurface128_Gray_Mat_0: THREE.Mesh;
    polySurface129_Tires_Mat_0: THREE.Mesh;
    polySurface130_Orange_Mat_0: THREE.Mesh;
    polySurface131_Orange_Mat_0: THREE.Mesh;
    polySurface132_Tires_Mat_0: THREE.Mesh;
    polySurface133_Gray_Mat_0: THREE.Mesh;
    polySurface134_Gray_Mat_0: THREE.Mesh;
    polySurface135_Inserts_Mat_0: THREE.Mesh;
    polySurface136_Inserts_Mat_0: THREE.Mesh;
  };
  materials: {
    Inserts_Mat: THREE.MeshStandardMaterial;
    Headlights_Mat: THREE.MeshStandardMaterial;
    Glass_Mat: THREE.MeshStandardMaterial;
    Gray_Mat: THREE.MeshStandardMaterial;
    Body_Mat: THREE.MeshPhysicalMaterial;
    Orange_Mat: THREE.MeshStandardMaterial;
    Tires_Mat: THREE.MeshStandardMaterial;
    Blinkers_Mat: THREE.MeshPhysicalMaterial;
    Roof_Mat: THREE.MeshPhysicalMaterial;
  };
};

type ActionName = 'Take 001';
// type GLTFActions = Record<ActionName, THREE.AnimationAction> 
interface GLTFActions extends THREE.AnimationClip {
  name: ActionName;
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    '/piggy_van_junior_3d_print-transformed.glb'
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  const scroll = useScroll();
  useEffect(() => {
    if(actions['Take 001']?.play().paused) {
      actions['Take 001'].play().paused = true
    }
  }, []);

  useFrame((state, delta) => {
    const action = actions['Take 001'];
    // Action.time is the clip duration multiplied with the normalized scroll offset (0-1)
    action.time = action.getClip().duration * scroll.offset;
    // Move camera along
    // state.camera.position.set(
    //   Math.sin(scroll.offset) * 10,
    //   Math.atan(scroll.offset * Math.PI * 2) * 5,
    //   Math.cos((scroll.offset * Math.PI) / 2) * 10
    // );
    // state.camera.zoom = 10 - scroll.offset * 0.5;
    state.camera.lookAt(0, 0, 0);
    state.camera.updateProjectionMatrix();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name='0e131489b49f4969842473ba44a18899fbx'
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name='Object_2'>
              <group name='RootNode'>
                <group name='Piggy_JR_Animate'>
                  <group name='polySurface82' position={[0, 2.55, 4.63]}>
                    <mesh
                      name='polySurface82_Inserts_Mat_0'
                      geometry={nodes.polySurface82_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface83' position={[1.95, 2.57, 4.67]}>
                    <mesh
                      name='polySurface83_Headlights_Mat_0'
                      geometry={nodes.polySurface83_Headlights_Mat_0.geometry}
                      material={materials.Headlights_Mat}
                    />
                  </group>
                  <group name='polySurface84' position={[-1.95, 2.57, 4.67]}>
                    <mesh
                      name='polySurface84_Headlights_Mat_0'
                      geometry={nodes.polySurface84_Headlights_Mat_0.geometry}
                      material={materials.Headlights_Mat}
                    />
                  </group>
                  <group name='polySurface85' position={[0, 6.49, 2.77]}>
                    <mesh
                      name='polySurface85_Glass_Mat_0'
                      geometry={nodes.polySurface85_Glass_Mat_0.geometry}
                      material={materials.Glass_Mat}
                    />
                  </group>
                  <group name='polySurface86' position={[0, 6.43, 3]}>
                    <mesh
                      name='polySurface86_Gray_Mat_0'
                      geometry={nodes.polySurface86_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface87' position={[0, 3.16, 4.23]}>
                    <mesh
                      name='polySurface87_Body_Mat_0'
                      geometry={nodes.polySurface87_Body_Mat_0.geometry}
                      material={materials.Body_Mat}
                    />
                  </group>
                  <group name='polySurface88' position={[0, 1.54, 5.17]}>
                    <mesh
                      name='polySurface88_Gray_Mat_0'
                      geometry={nodes.polySurface88_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface89' position={[1.43, 5.54, -4.6]}>
                    <mesh
                      name='polySurface89_Body_Mat_0'
                      geometry={nodes.polySurface89_Body_Mat_0.geometry}
                      material={materials.Body_Mat}
                    />
                  </group>
                  <group name='polySurface90' position={[1.29, 5.69, -4.34]}>
                    <mesh
                      name='polySurface90_Glass_Mat_0'
                      geometry={nodes.polySurface90_Glass_Mat_0.geometry}
                      material={materials.Glass_Mat}
                    />
                  </group>
                  <group name='polySurface91' position={[-1.49, 5.54, -4.49]}>
                    <mesh
                      name='polySurface91_Body_Mat_0'
                      geometry={nodes.polySurface91_Body_Mat_0.geometry}
                      material={materials.Body_Mat}
                    />
                  </group>
                  <group name='polySurface93' position={[-1.29, 5.69, -4.34]}>
                    <mesh
                      name='polySurface93_Glass_Mat_0'
                      geometry={nodes.polySurface93_Glass_Mat_0.geometry}
                      material={materials.Glass_Mat}
                    />
                  </group>
                  <group name='polySurface94' position={[0.81, 4.91, -4.65]}>
                    <mesh
                      name='polySurface94_Gray_Mat_0'
                      geometry={nodes.polySurface94_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface95' position={[1.29, 5.69, -4.47]}>
                    <mesh
                      name='polySurface95_Gray_Mat_0'
                      geometry={nodes.polySurface95_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface96' position={[0, 5.28, 0.25]}>
                    <mesh
                      name='polySurface96_Gray_Mat_0'
                      geometry={nodes.polySurface96_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface97' position={[0, 3.53, 3.42]}>
                    <mesh
                      name='polySurface97_Gray_Mat_0'
                      geometry={nodes.polySurface97_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface98' position={[2.52, 6, 1.74]}>
                    <mesh
                      name='polySurface98_Glass_Mat_0'
                      geometry={nodes.polySurface98_Glass_Mat_0.geometry}
                      material={materials.Glass_Mat}
                    />
                  </group>
                  <group name='polySurface99' position={[2.78, 3.3, 0.92]}>
                    <mesh
                      name='polySurface99_Gray_Mat_0'
                      geometry={nodes.polySurface99_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface100' position={[2.65, 6, 1.74]}>
                    <mesh
                      name='polySurface100_Gray_Mat_0'
                      geometry={nodes.polySurface100_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface103' position={[2.78, 4.92, -0.12]}>
                    <mesh
                      name='polySurface103_Body_Mat_0'
                      geometry={nodes.polySurface103_Body_Mat_0.geometry}
                      material={materials.Body_Mat}
                    />
                    <mesh
                      name='polySurface103_Body_Mat_0_1'
                      geometry={nodes.polySurface103_Body_Mat_0_1.geometry}
                      material={materials.Body_Mat}
                    />
                    <mesh
                      name='polySurface103_Body_Mat_0_2'
                      geometry={nodes.polySurface103_Body_Mat_0_2.geometry}
                      material={materials.Body_Mat}
                    />
                  </group>
                  <group name='polySurface104' position={[-2.78, 4.92, -0.12]}>
                    <mesh
                      name='polySurface104_Body_Mat_0'
                      geometry={nodes.polySurface104_Body_Mat_0.geometry}
                      material={materials.Body_Mat}
                    />
                    <mesh
                      name='polySurface104_Body_Mat_0_1'
                      geometry={nodes.polySurface104_Body_Mat_0_1.geometry}
                      material={materials.Body_Mat}
                    />
                    <mesh
                      name='polySurface104_Body_Mat_0_2'
                      geometry={nodes.polySurface104_Body_Mat_0_2.geometry}
                      material={materials.Body_Mat}
                    />
                  </group>
                  <group name='polySurface105' position={[2.71, 0.88, -2.21]}>
                    <mesh
                      name='polySurface105_Orange_Mat_0'
                      geometry={nodes.polySurface105_Orange_Mat_0.geometry}
                      material={materials.Orange_Mat}
                    />
                  </group>
                  <group name='polySurface106' position={[2.35, 0.88, -2.21]}>
                    <mesh
                      name='polySurface106_Tires_Mat_0'
                      geometry={nodes.polySurface106_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface107' position={[0, 0.78, -2.2]}>
                    <mesh
                      name='polySurface107_Tires_Mat_0'
                      geometry={nodes.polySurface107_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface108' position={[-1.65, 1.67, -4.61]}>
                    <mesh
                      name='polySurface108_Blinkers_Mat_0'
                      geometry={nodes.polySurface108_Blinkers_Mat_0.geometry}
                      material={materials.Blinkers_Mat}
                    />
                  </group>
                  <group name='polySurface109' position={[1.65, 1.67, -4.61]}>
                    <mesh
                      name='polySurface109_Blinkers_Mat_0'
                      geometry={nodes.polySurface109_Blinkers_Mat_0.geometry}
                      material={materials.Blinkers_Mat}
                    />
                  </group>
                  <group name='polySurface110' position={[0, 1.7, -4.56]}>
                    <mesh
                      name='polySurface110_Inserts_Mat_0'
                      geometry={nodes.polySurface110_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface111' position={[0, 1.9, -0.56]}>
                    <mesh
                      name='polySurface111_Gray_Mat_0'
                      geometry={nodes.polySurface111_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface112' position={[1.86, 1.47, 0.57]}>
                    <mesh
                      name='polySurface112_Gray_Mat_0'
                      geometry={nodes.polySurface112_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface113' position={[2.71, 0.88, 2.9]}>
                    <mesh
                      name='polySurface113_Orange_Mat_0'
                      geometry={nodes.polySurface113_Orange_Mat_0.geometry}
                      material={materials.Orange_Mat}
                    />
                  </group>
                  <group name='polySurface114' position={[2.35, 0.88, 2.9]}>
                    <mesh
                      name='polySurface114_Tires_Mat_0'
                      geometry={nodes.polySurface114_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface115' position={[0, 0.78, 2.9]}>
                    <mesh
                      name='polySurface115_Tires_Mat_0'
                      geometry={nodes.polySurface115_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface116' position={[0, 8.9, -2.02]}>
                    <mesh
                      name='polySurface116_Inserts_Mat_0'
                      geometry={nodes.polySurface116_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface117' position={[0, 8.95, -2.02]}>
                    <mesh
                      name='polySurface117_Inserts_Mat_0'
                      geometry={nodes.polySurface117_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface119' position={[0, 8.84, 2.07]}>
                    <mesh
                      name='polySurface119_Blinkers_Mat_0'
                      geometry={nodes.polySurface119_Blinkers_Mat_0.geometry}
                      material={materials.Blinkers_Mat}
                    />
                  </group>
                  <group name='polySurface122' position={[0, 8.73, -0.9]}>
                    <mesh
                      name='polySurface122_Roof_Mat_0'
                      geometry={nodes.polySurface122_Roof_Mat_0.geometry}
                      material={materials.Roof_Mat}
                    />
                    <mesh
                      name='polySurface122_Roof_Mat_0_1'
                      geometry={nodes.polySurface122_Roof_Mat_0_1.geometry}
                      material={materials.Roof_Mat}
                    />
                  </group>
                  <group name='polySurface123' position={[0, 9.03, 0.5]}>
                    <mesh
                      name='polySurface123_Roof_Mat_0'
                      geometry={nodes.polySurface123_Roof_Mat_0.geometry}
                      material={materials.Roof_Mat}
                    />
                  </group>
                  <group name='polySurface124' position={[2.52, 5.45, -2.02]}>
                    <mesh
                      name='polySurface124_Inserts_Mat_0'
                      geometry={nodes.polySurface124_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface125' position={[2.77, 5.45, -2.02]}>
                    <mesh
                      name='polySurface125_Inserts_Mat_0'
                      geometry={nodes.polySurface125_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface126' position={[-2.65, 6, 1.74]}>
                    <mesh
                      name='polySurface126_Gray_Mat_0'
                      geometry={nodes.polySurface126_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface127' position={[-2.52, 6, 1.74]}>
                    <mesh
                      name='polySurface127_Glass_Mat_0'
                      geometry={nodes.polySurface127_Glass_Mat_0.geometry}
                      material={materials.Glass_Mat}
                    />
                  </group>
                  <group name='polySurface128' position={[-2.78, 3.3, 0.92]}>
                    <mesh
                      name='polySurface128_Gray_Mat_0'
                      geometry={nodes.polySurface128_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface129' position={[-2.35, 0.88, 2.9]}>
                    <mesh
                      name='polySurface129_Tires_Mat_0'
                      geometry={nodes.polySurface129_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface130' position={[-2.71, 0.88, 2.9]}>
                    <mesh
                      name='polySurface130_Orange_Mat_0'
                      geometry={nodes.polySurface130_Orange_Mat_0.geometry}
                      material={materials.Orange_Mat}
                    />
                  </group>
                  <group name='polySurface131' position={[-2.71, 0.88, -2.21]}>
                    <mesh
                      name='polySurface131_Orange_Mat_0'
                      geometry={nodes.polySurface131_Orange_Mat_0.geometry}
                      material={materials.Orange_Mat}
                    />
                  </group>
                  <group name='polySurface132' position={[-2.35, 0.88, -2.21]}>
                    <mesh
                      name='polySurface132_Tires_Mat_0'
                      geometry={nodes.polySurface132_Tires_Mat_0.geometry}
                      material={materials.Tires_Mat}
                    />
                  </group>
                  <group name='polySurface133' position={[-1.86, 1.47, 0.57]}>
                    <mesh
                      name='polySurface133_Gray_Mat_0'
                      geometry={nodes.polySurface133_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface134' position={[-1.29, 5.69, -4.47]}>
                    <mesh
                      name='polySurface134_Gray_Mat_0'
                      geometry={nodes.polySurface134_Gray_Mat_0.geometry}
                      material={materials.Gray_Mat}
                    />
                  </group>
                  <group name='polySurface135' position={[-2.58, 5.45, -2.02]}>
                    <mesh
                      name='polySurface135_Inserts_Mat_0'
                      geometry={nodes.polySurface135_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                  <group name='polySurface136' position={[-2.7, 5.45, -2.02]}>
                    <mesh
                      name='polySurface136_Inserts_Mat_0'
                      geometry={nodes.polySurface136_Inserts_Mat_0.geometry}
                      material={materials.Inserts_Mat}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/piggy_van_junior_3d_print-transformed.glb');
